name: Packages

on:
  push:
    branches:
      - main
      - stable-v[0-9]+.x.x

jobs:
  publish:
    runs-on: ubuntu-20.04
    concurrency:
      group: release
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Setup Corepack
        run: corepack enable
      
      - name: Setup yarn
        run: |
          yarn config set nodeLinker node-modules
          yarn config set enableImmutableInstalls false
          yarn config ser npmAuthToken $NPM_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: yarn install
      - run: yarn build
      - run: yarn build:publish
      - run: yarn build:change-typings
      - run: yarn build:change-versions

      - name: Publish
        run: yarn publish:all
